-- ============================================================================
-- Leo Shift — 신규 스키마 V1
--
-- 설계 근거: docs/domain-design.md
-- 기존 db/migration/V1~V11은 폐기한다. 이 스키마는 기존 데이터를 받지 않는다.
--
-- 원칙
--   1. 캘린더는 사람(또는 그룹)의 것이다. 캘린더가 여러 사람을 담지 않는다.
--   2. 그룹은 데이터를 담지 않는다. 멤버십에 기간이 있고, 화면은 조회로 만든다.
--   3. 모든 시각은 timestamptz. 날짜만인 것은 date.
--   4. 참조 무결성은 DB가 지킨다. 애플리케이션 검증에 의존하지 않는다.
--   5. 모든 FK에 ON DELETE를 명시한다. 사용자 삭제 경로를 막지 않는다.
--   6. ddl-auto=validate 전제. Hibernate가 스키마를 바꾸지 않는다.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS btree_gist;   -- work_rules 기간 겹침 방지에 필요

-- ---------------------------------------------------------------------------
-- 공통: updated_at 자동 갱신
-- JPA @PreUpdate에 의존하면 벌크 연산이 전부 우회한다. DB에서 보장한다.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ===========================================================================
-- 1. 사용자와 인증
-- ===========================================================================

CREATE TABLE users (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT         NOT NULL,
    password_hash TEXT,                        -- OAuth 전용 계정은 NULL
    name          VARCHAR(100) NOT NULL,
    nickname      VARCHAR(50),
    picture_url   TEXT,
    color_tag     VARCHAR(16),                 -- 겹쳐 보기에서 이 사람의 색
    time_zone     VARCHAR(64)  NOT NULL DEFAULT 'Asia/Seoul',
    locale        VARCHAR(16)  NOT NULL DEFAULT 'ko-KR',
    role          VARCHAR(16)  NOT NULL DEFAULT 'USER',
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    -- 비밀번호 변경·계정 정지 시 올린다. 발급된 모든 토큰이 즉시 무효가 된다.
    token_version INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ,
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT users_role_chk   CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT users_status_chk CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

-- 이메일 대소문자를 구분하지 않는다.
-- 기존 스키마는 case-sensitive라 Foo@x.com과 foo@x.com이 별개 계정이 됐고,
-- 초대가 대소문자 때문에 조용히 실패했다.
CREATE UNIQUE INDEX users_email_uq ON users (lower(email)) WHERE deleted_at IS NULL;

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 소셜 로그인 연결. 사용자당 여러 provider를 붙일 수 있다.
-- 기존 코드는 이메일 문자열만 보고 계정을 연결했고 email_verified를 확인하지
-- 않았다. provider + provider_uid로 연결하는 게 맞다.
CREATE TABLE user_identities (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider       VARCHAR(32)  NOT NULL,
    provider_uid   VARCHAR(255) NOT NULL,
    email          TEXT,
    email_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT user_identities_provider_chk CHECK (provider IN ('GOOGLE', 'APPLE', 'KAKAO')),
    CONSTRAINT user_identities_uq UNIQUE (provider, provider_uid)
);

CREATE INDEX user_identities_user_idx ON user_identities (user_id);

CREATE TRIGGER user_identities_set_updated_at BEFORE UPDATE ON user_identities
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 리프레시 토큰을 저장한다. 기존 구조는 저장소가 없어서 로그아웃도, 폐기도,
-- 재사용 탐지도 불가능했다. 원문이 아니라 해시를 저장한다.
CREATE TABLE refresh_tokens (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  TEXT        NOT NULL,
    family_id   UUID        NOT NULL,    -- 회전 계열. 재사용 탐지 시 계열 전체를 폐기
    issued_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    replaced_by BIGINT      REFERENCES refresh_tokens (id) ON DELETE SET NULL,
    user_agent  TEXT,
    CONSTRAINT refresh_tokens_hash_uq UNIQUE (token_hash)
);

CREATE INDEX refresh_tokens_user_idx   ON refresh_tokens (user_id) WHERE revoked_at IS NULL;
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id);
CREATE INDEX refresh_tokens_expiry_idx ON refresh_tokens (expires_at) WHERE revoked_at IS NULL;


CREATE TABLE user_settings (
    user_id                  BIGINT      PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    default_reminder_minutes INTEGER     NOT NULL DEFAULT 60,
    week_starts_on           SMALLINT    NOT NULL DEFAULT 1,   -- ISO-8601: 월=1 ... 일=7
    theme                    VARCHAR(16) NOT NULL DEFAULT 'SYSTEM',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT user_settings_week_chk  CHECK (week_starts_on BETWEEN 1 AND 7),
    CONSTRAINT user_settings_theme_chk CHECK (theme IN ('SYSTEM', 'LIGHT', 'DARK'))
);

-- 주의: 기본 캘린더는 여기 두지 않는다. calendars.is_default로 옮겼다.
-- 기존 user_settings.default_calendar_id는 ON DELETE가 없어서
-- 공유된 캘린더를 삭제할 때 FK 위반 500을 냈다.

CREATE TRIGGER user_settings_set_updated_at BEFORE UPDATE ON user_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 2. 그룹 (프로젝트 / 직장 / 가족 / 친구)
-- ===========================================================================

CREATE TABLE groups (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 소유자가 계정을 삭제하면 그룹도 사라진다.
    -- 애플리케이션은 삭제 전에 소유권 이전을 먼저 제안해야 한다.
    owner_user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          VARCHAR(100) NOT NULL,
    kind          VARCHAR(16)  NOT NULL DEFAULT 'PROJECT',
    description   TEXT,
    color         VARCHAR(16),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ,
    CONSTRAINT groups_kind_chk
        CHECK (kind IN ('PROJECT', 'WORKPLACE', 'FAMILY', 'FRIENDS', 'OTHER'))
);

CREATE UNIQUE INDEX groups_owner_name_uq
    ON groups (owner_user_id, lower(name)) WHERE deleted_at IS NULL;

CREATE TRIGGER groups_set_updated_at BEFORE UPDATE ON groups
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 멤버십에 기간이 있는 것이 이 설계의 핵심이다.
-- "프로젝트 단위로 변경되는 인원"을 여기서 해결한다.
-- 사람을 지우는 게 아니라 left_on을 적는다. 8월 화면에는 8월에 소속된
-- 사람만 나오고, 6월 화면에는 6월에 있던 사람이 그대로 나온다.
CREATE TABLE group_members (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT      NOT NULL REFERENCES groups (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id)  ON DELETE CASCADE,
    role       VARCHAR(16) NOT NULL DEFAULT 'MEMBER',
    joined_on  DATE        NOT NULL DEFAULT CURRENT_DATE,
    left_on    DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT group_members_role_chk   CHECK (role IN ('OWNER', 'MEMBER')),
    CONSTRAINT group_members_period_chk CHECK (left_on IS NULL OR left_on >= joined_on)
);

-- 나갔다가 다시 들어올 수 있으므로 (group_id, user_id) 전체 유니크는 걸지 않는다.
-- 대신 "현재 활성 멤버십은 하나"만 강제한다.
CREATE UNIQUE INDEX group_members_active_uq
    ON group_members (group_id, user_id) WHERE left_on IS NULL;

CREATE INDEX group_members_user_active_idx ON group_members (user_id) WHERE left_on IS NULL;
CREATE INDEX group_members_period_idx      ON group_members (group_id, joined_on, left_on);

CREATE TRIGGER group_members_set_updated_at BEFORE UPDATE ON group_members
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 3. 캘린더
-- ===========================================================================

CREATE TABLE calendars (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id  BIGINT       REFERENCES users (id)  ON DELETE CASCADE,
    owner_group_id BIGINT       REFERENCES groups (id) ON DELETE CASCADE,
    name           VARCHAR(100) NOT NULL,
    description    TEXT,
    color          VARCHAR(16),
    kind           VARCHAR(16)  NOT NULL,
    time_zone      VARCHAR(64)  NOT NULL DEFAULT 'Asia/Seoul',
    is_default     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    -- WORK  : 근무 규칙·휴가가 붙는 캘린더. 사용자당 보통 하나
    -- GENERAL: 개인 일정, 그룹 공동 일정
    CONSTRAINT calendars_kind_chk CHECK (kind IN ('WORK', 'GENERAL')),
    -- 소유자는 사용자이거나 그룹이거나, 정확히 하나
    CONSTRAINT calendars_owner_chk
        CHECK (num_nonnulls(owner_user_id, owner_group_id) = 1),
    -- 그룹 캘린더에는 근무 규칙이 붙지 않는다
    CONSTRAINT calendars_group_kind_chk
        CHECK (owner_group_id IS NULL OR kind = 'GENERAL')
);

CREATE INDEX calendars_owner_user_idx  ON calendars (owner_user_id)  WHERE deleted_at IS NULL;
CREATE INDEX calendars_owner_group_idx ON calendars (owner_group_id) WHERE deleted_at IS NULL;

-- 사용자당 기본 캘린더는 하나
CREATE UNIQUE INDEX calendars_default_uq
    ON calendars (owner_user_id) WHERE is_default AND deleted_at IS NULL;

CREATE TRIGGER calendars_set_updated_at BEFORE UPDATE ON calendars
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 4. 근무 — 일정 타입, 반복 규칙, 휴가, 날짜별 예외
-- ===========================================================================

-- 캘린더별 코드 사전. 이름·색·시간은 사용자가 정하고, category만 시스템 값이다.
-- category가 시스템 값이어야 그룹 타임라인에서 사람마다 다른 코드를 써도
-- "누가 근무 중이고 누가 휴가인지" 집계할 수 있다.
CREATE TABLE schedule_types (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id      BIGINT       NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    code             VARCHAR(32)  NOT NULL,
    name             VARCHAR(100) NOT NULL,
    color            VARCHAR(16)  NOT NULL DEFAULT '#94A3B8',
    category         VARCHAR(16)  NOT NULL,
    start_time       TIME,
    end_time         TIME,
    crosses_midnight BOOLEAN      NOT NULL DEFAULT FALSE,   -- 야간 22:00-06:00
    half_day         BOOLEAN      NOT NULL DEFAULT FALSE,   -- 반차
    sort_order       INTEGER      NOT NULL DEFAULT 100,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- 아래 UNIQUE는 다른 표에서 복합 FK의 참조 대상이 된다. 반드시 유지할 것.
    CONSTRAINT schedule_types_code_uq UNIQUE (calendar_id, code),
    CONSTRAINT schedule_types_code_upper_chk CHECK (code = upper(code)),
    CONSTRAINT schedule_types_category_chk   CHECK (category IN ('WORK', 'OFF', 'LEAVE')),
    CONSTRAINT schedule_types_worktime_chk
        CHECK (category <> 'WORK' OR (start_time IS NOT NULL AND end_time IS NOT NULL)),
    CONSTRAINT schedule_types_halfday_chk
        CHECK (NOT half_day OR category = 'LEAVE')
);

CREATE INDEX schedule_types_calendar_idx ON schedule_types (calendar_id, sort_order, code);

CREATE TRIGGER schedule_types_set_updated_at BEFORE UPDATE ON schedule_types
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 반복 근무 규칙. 단일 원시 타입: (기준일, 주기, 시퀀스).
--   주5일    : cycle_length=7,  ["WORK","WORK","WORK","WORK","WORK","OFF","OFF"]
--   격일제   : cycle_length=2,  ["ON","OFF"]
--   4조 3교대: cycle_length=12, ["D","D","D","A","A","A","N","N","N","O","O","O"]
-- 요일 규칙은 주기가 7인 순환 패턴일 뿐이므로 별도 표를 두지 않는다.
CREATE TABLE work_rules (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id      BIGINT      NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    anchor_date      DATE        NOT NULL,   -- 시퀀스 0번이 적용되는 날
    cycle_length     INTEGER     NOT NULL,
    code_sequence    JSONB       NOT NULL,   -- schedule_types.code의 배열
    effective_from   DATE        NOT NULL,
    effective_to     DATE,                   -- NULL이면 무기한
    source_preset_id VARCHAR(64),            -- 어떤 프리셋에서 시작했는지 (출처 기록)
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT work_rules_cycle_chk  CHECK (cycle_length BETWEEN 1 AND 366),
    CONSTRAINT work_rules_seq_chk    CHECK (jsonb_typeof(code_sequence) = 'array'),
    CONSTRAINT work_rules_seq_len_chk CHECK (jsonb_array_length(code_sequence) = cycle_length),
    CONSTRAINT work_rules_period_chk CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

-- 같은 캘린더에서 유효기간이 겹치는 규칙을 만들 수 없다.
-- 기존 코드에서 월 뷰와 일 상세가 서로 다른 근무를 보여준 원인이 여기 있었다.
-- 겹침이 구조적으로 불가능하면 "그날의 규칙"이 항상 하나로 정해진다.
ALTER TABLE work_rules ADD CONSTRAINT work_rules_no_overlap
    EXCLUDE USING gist (
        calendar_id WITH =,
        daterange(effective_from, effective_to, '[]') WITH &&
    );

CREATE INDEX work_rules_lookup_idx ON work_rules (calendar_id, effective_from DESC);

CREATE TRIGGER work_rules_set_updated_at BEFORE UPDATE ON work_rules
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN work_rules.code_sequence IS
    'schedule_types.code 배열. JSONB라 FK가 걸리지 않으므로, 코드 이름 변경·삭제 시 '
    '애플리케이션이 이 컬럼을 함께 갱신해야 한다. (leaves/day_overrides는 FK가 처리)';


-- 휴가·부재. 날짜 범위로 저장해서 "8/15~8/20 연차"가 한 줄이 된다.
-- 기존 calendar_leave_entries의 target_user_id는 없앴다.
-- 캘린더가 이미 한 사람의 것이므로 대상 사용자 컬럼이 필요 없다.
CREATE TABLE leaves (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id        BIGINT      NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    start_date         DATE        NOT NULL,
    end_date           DATE        NOT NULL,
    schedule_type_code VARCHAR(32) NOT NULL,   -- category='LEAVE'인 코드
    note               TEXT,
    created_by_user_id BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    version            INTEGER     NOT NULL DEFAULT 0,
    CONSTRAINT leaves_period_chk CHECK (end_date >= start_date),
    -- 복합 FK. ON UPDATE CASCADE 덕분에 코드 이름을 바꾸면 여기가 자동으로 따라온다.
    -- ON DELETE RESTRICT라 사용 중인 코드는 지워지지 않는다.
    CONSTRAINT leaves_type_fk FOREIGN KEY (calendar_id, schedule_type_code)
        REFERENCES schedule_types (calendar_id, code) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX leaves_range_idx ON leaves (calendar_id, start_date, end_date);

CREATE TRIGGER leaves_set_updated_at BEFORE UPDATE ON leaves
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 날짜별 예외와 메모. 규칙과 휴가를 덮어쓴다.
-- 하루 해석 순서: work_rules → leaves → day_overrides
CREATE TABLE day_overrides (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id        BIGINT      NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    on_date            DATE        NOT NULL,
    schedule_type_code VARCHAR(32),            -- NULL이면 메모만 있는 날
    note               TEXT,
    author_user_id     BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    version            INTEGER     NOT NULL DEFAULT 0,   -- 낙관적 잠금
    CONSTRAINT day_overrides_uq UNIQUE (calendar_id, on_date),
    CONSTRAINT day_overrides_content_chk
        CHECK (schedule_type_code IS NOT NULL OR note IS NOT NULL),
    CONSTRAINT day_overrides_type_fk FOREIGN KEY (calendar_id, schedule_type_code)
        REFERENCES schedule_types (calendar_id, code) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX day_overrides_author_idx ON day_overrides (author_user_id);

CREATE TRIGGER day_overrides_set_updated_at BEFORE UPDATE ON day_overrides
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 5. 일정 (시간 단위)
-- ===========================================================================

CREATE TABLE events (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id        BIGINT       NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    title              VARCHAR(200) NOT NULL,
    description        TEXT,
    location           VARCHAR(200),
    starts_at          TIMESTAMPTZ  NOT NULL,
    ends_at            TIMESTAMPTZ  NOT NULL,
    all_day            BOOLEAN      NOT NULL DEFAULT FALSE,
    -- 반복 전개는 이 시간대 기준으로 한다. 서머타임·시간대 이동에서
    -- "매주 화 20:30"이 벽시계 기준으로 유지되게 하려면 시각만으로는 부족하다.
    time_zone          VARCHAR(64)  NOT NULL DEFAULT 'Asia/Seoul',
    rrule              TEXT,                    -- RFC 5545 RRULE. 단발이면 NULL
    recurrence_end     TIMESTAMPTZ,             -- 반복 마지막 시각. 무한이면 NULL
    created_by_user_id BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            INTEGER      NOT NULL DEFAULT 0,
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT events_period_chk CHECK (ends_at >= starts_at)
);

-- 단발 일정 조회. 반복은 rrule을 전개해야 하므로 별도 인덱스로 뽑는다.
CREATE INDEX events_range_idx ON events (calendar_id, starts_at, ends_at)
    WHERE deleted_at IS NULL AND rrule IS NULL;

CREATE INDEX events_recurring_idx ON events (calendar_id, starts_at)
    WHERE deleted_at IS NULL AND rrule IS NOT NULL;

CREATE TRIGGER events_set_updated_at BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- 반복 중 예외가 생긴 회차만 저장한다 (iCalendar RECURRENCE-ID 방식).
-- 휴강·보강, "이번 주 회의만 시간 변경"이 전부 여기로 들어온다.
-- 취소를 삭제가 아니라 상태로 남기므로 달력에 "휴강"으로 표시할 수 있다.
CREATE TABLE event_occurrences (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT       NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    original_start TIMESTAMPTZ  NOT NULL,   -- 원래 몇 회차인지 식별
    status         VARCHAR(16)  NOT NULL,
    starts_at      TIMESTAMPTZ,             -- 옮긴 경우 새 시각
    ends_at        TIMESTAMPTZ,
    title          VARCHAR(200),            -- 이 회차만 다른 제목
    note           TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT event_occurrences_uq UNIQUE (event_id, original_start),
    CONSTRAINT event_occurrences_status_chk
        CHECK (status IN ('CANCELLED', 'MOVED', 'MODIFIED')),
    CONSTRAINT event_occurrences_moved_chk
        CHECK (status = 'CANCELLED' OR starts_at IS NOT NULL),
    CONSTRAINT event_occurrences_period_chk
        CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at >= starts_at)
);

CREATE INDEX event_occurrences_event_idx ON event_occurrences (event_id, original_start);

CREATE TRIGGER event_occurrences_set_updated_at BEFORE UPDATE ON event_occurrences
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 6. 공유
-- ===========================================================================

-- 공유 한 건 = 누구에게(사람 또는 그룹) × 무엇을(캘린더) × 어떻게(권한·공개)
--
-- UI의 "근무만 / 바쁨만 / 전체" 3단계는 두 축의 조합으로 구현된다.
--   근무만 → WORK 캘린더만 공유, visibility=FULL
--   바쁨만 → 전 캘린더 공유, visibility=BUSY_ONLY
--   전체   → 전 캘린더 공유, visibility=FULL
-- 그래서 이 표의 visibility 자체는 두 값만 가진다.
CREATE TABLE calendar_shares (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id        BIGINT      NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    grantee_user_id    BIGINT      REFERENCES users (id)  ON DELETE CASCADE,
    grantee_group_id   BIGINT      REFERENCES groups (id) ON DELETE CASCADE,
    permission         VARCHAR(16) NOT NULL DEFAULT 'VIEW',
    visibility         VARCHAR(16) NOT NULL DEFAULT 'FULL',
    status             VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_by_user_id BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    responded_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT calendar_shares_grantee_chk
        CHECK (num_nonnulls(grantee_user_id, grantee_group_id) = 1),
    CONSTRAINT calendar_shares_permission_chk CHECK (permission IN ('VIEW', 'EDIT')),
    CONSTRAINT calendar_shares_visibility_chk CHECK (visibility IN ('FULL', 'BUSY_ONLY')),
    CONSTRAINT calendar_shares_status_chk
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED'))
);

-- 살아 있는 공유는 대상당 하나. 취소된 건은 기록으로 남긴다.
CREATE UNIQUE INDEX calendar_shares_user_uq
    ON calendar_shares (calendar_id, grantee_user_id)
    WHERE grantee_user_id IS NOT NULL AND status <> 'REVOKED';

CREATE UNIQUE INDEX calendar_shares_group_uq
    ON calendar_shares (calendar_id, grantee_group_id)
    WHERE grantee_group_id IS NOT NULL AND status <> 'REVOKED';

-- 접근 권한 판정의 핫패스. 기존 스키마는 부분 인덱스의 조건(target_type)을
-- 쿼리가 걸지 않아서 매 요청마다 seq scan이 났다.
-- 아래 인덱스는 status='ACCEPTED'로 걸려 있으므로,
-- 조회 쿼리에 반드시 status = 'ACCEPTED' 조건을 넣어야 인덱스를 탄다.
CREATE INDEX calendar_shares_grantee_user_idx
    ON calendar_shares (grantee_user_id, calendar_id) WHERE status = 'ACCEPTED';

CREATE INDEX calendar_shares_grantee_group_idx
    ON calendar_shares (grantee_group_id, calendar_id) WHERE status = 'ACCEPTED';

CREATE INDEX calendar_shares_calendar_idx ON calendar_shares (calendar_id);

CREATE TRIGGER calendar_shares_set_updated_at BEFORE UPDATE ON calendar_shares
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 7. 외부 캘린더 연동
-- ===========================================================================

CREATE TABLE external_sources (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id           BIGINT       NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    name                  VARCHAR(100) NOT NULL,
    feed_url              TEXT         NOT NULL,
    color                 VARCHAR(16),
    display_mode          VARCHAR(16)  NOT NULL DEFAULT 'BADGE',
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    sync_interval_minutes INTEGER      NOT NULL DEFAULT 360,
    last_synced_at        TIMESTAMPTZ,
    last_error            TEXT,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- 같은 피드를 여러 번 구독하면 동기화마다 이벤트가 통째로 중복된다
    CONSTRAINT external_sources_feed_uq UNIQUE (calendar_id, feed_url),
    CONSTRAINT external_sources_display_chk CHECK (display_mode IN ('BADGE', 'INLINE', 'HIDDEN'))
);

CREATE INDEX external_sources_sync_idx
    ON external_sources (last_synced_at) WHERE active;

CREATE TRIGGER external_sources_set_updated_at BEFORE UPDATE ON external_sources
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


CREATE TABLE external_events (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   BIGINT       NOT NULL REFERENCES external_sources (id) ON DELETE CASCADE,
    uid         VARCHAR(512) NOT NULL,
    title       VARCHAR(500),
    starts_at   TIMESTAMPTZ  NOT NULL,
    ends_at     TIMESTAMPTZ  NOT NULL,
    all_day     BOOLEAN      NOT NULL DEFAULT FALSE,
    location    VARCHAR(500),
    description TEXT,
    synced_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT external_events_uq UNIQUE (source_id, uid, starts_at),
    CONSTRAINT external_events_period_chk CHECK (ends_at >= starts_at)
);

CREATE INDEX external_events_range_idx ON external_events (source_id, starts_at, ends_at);


-- ===========================================================================
-- 8. 내보내기용 구독 토큰
--    내 근무표를 구글 캘린더에서 볼 수 있게 하는 읽기 전용 .ics 주소
-- ===========================================================================

CREATE TABLE calendar_feed_tokens (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_id  BIGINT      NOT NULL REFERENCES calendars (id) ON DELETE CASCADE,
    token        UUID        NOT NULL DEFAULT gen_random_uuid(),
    visibility   VARCHAR(16) NOT NULL DEFAULT 'FULL',
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,
    CONSTRAINT calendar_feed_tokens_uq UNIQUE (token),
    CONSTRAINT calendar_feed_tokens_visibility_chk CHECK (visibility IN ('FULL', 'BUSY_ONLY'))
);

CREATE INDEX calendar_feed_tokens_calendar_idx
    ON calendar_feed_tokens (calendar_id) WHERE revoked_at IS NULL;
