ALTER TABLE external_calendar_sources
    ADD COLUMN IF NOT EXISTS display_mode VARCHAR(32) NOT NULL DEFAULT 'TAG',
    ADD COLUMN IF NOT EXISTS date_text_color VARCHAR(20) NOT NULL DEFAULT '#FF3B30',
    ADD COLUMN IF NOT EXISTS border_color VARCHAR(20) NOT NULL DEFAULT '#FF3B30';
